### PR TITLE
Rm credentials

### PR DESCRIPTION
**Pull request by liamgriffiths**
Hey, thanks for your interest in Grailed!

We noticed a scraper making lots of requests last night - was that this project? What are your plans for this?

By the way you should try to avoid publishing usernames and passwords in your code. One way to keep them out is to use environment variables. This PR makes the change. 

If you have accounts out there that use that username or password I would go change them now. There are numerous bots that scrape github for information like this and use it to compromise accounts.

### CODE REVIEW

**Comment by peterparkerspicklepatch** [comment]
@liamgriffiths That was me - I am so fucking sorry. This is my first Python project and I'm trying to figure out what the fuck I'm doing. 

I'm an Economist and very interested in Grailed. I wanted to collect data and use economics to make Grailed better. For instance one of the things I'm interested in is the economic impact or a price cut/bump. I think by tracking Grailed postings it's possible to predict sell price before, it's posted which is valuable to user. I'd love to talk to anyone at Grailed about this.

**Comment by liamgriffiths** [comment]
@peterparkerspicklepatch haha, well something seemed to be working :wink: 

Your project sounds cool. Putting more information out there to help buyers and sellers is something we'd like to do eventually. Also, I think it would be nice to have an easier way to access public grailed data so it wouldn't have to be scraped - we have to throttle requests so that a single user doesn't degrade the site for everyone else. 

Feel free to email us at help@grailed.com to chat more if you like, cheers!

**Comment by peterparkerspicklepatch** [comment]
Sending that out right now.

On Sat, Oct 10, 2015 at 6:38 PM, Liam Griffiths <notifications@github.com>
wrote:

> @peterparkerspicklepatch <https://github.com/peterparkerspicklepatch>
> haha, well something seemed to be working [image: :wink:]
>
> Your project sounds cool. Putting more information out there to help
> buyers and sellers is something we'd like to do eventually. Also, I think
> it would be nice to have an easier way to access public grailed data so it
> wouldn't have to be scraped - we have to throttle requests so that a single
> user doesn't degrade the site for everyone else.
>
> Feel free to email us at help@grailed.com to chat more if you like,
> cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peterparkerspicklepatch/grailed-webscraper/pull/1#issuecomment-147131214>
> .
>



-- 
Phillip Black
Economist Born & Raised

**Comment by peterparkerspicklepatch** [comment]
@liamgriffiths so can that ban be lifted lol?

**Comment by liamgriffiths** [comment]
Sure, sorry forgot to update that!

**Comment by peterparkerspicklepatch** [comment]
@liamgriffiths No response from the Engineering team when I shot them an e-mail. Does the team have a database any sort?

**Comment by liamgriffiths** [comment]
We don't have a database we are sharing publicly at the moment, but this is something we are considering in the future.

**Pull request merged**
